---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: default
  labels:
    app: order-deployment
spec:
  selector:
    matchLabels:
      app: order-deployment
  template:
    metadata:
      labels:
        app: order-deployment
    spec:
      containers:
        - name: order-service
          image: europe-west4-docker.pkg.dev/acoustic-atom-468009-u9/order-system-repository/order.service:0.0.1-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/postgres?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless.kafka.svc.cluster.local:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry.kafka.svc.cluster.local:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
  labels:
    app: order-service
spec:
  selector:
    app: order-deployment
  ports:
    - name: order-service-port
      protocol: TCP
      port: 8181
  type: LoadBalancer
  loadBalancerIP: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: default
  labels:
    app: payment-deployment
spec:
  selector:
    matchLabels:
      app: payment-deployment
  template:
    metadata:
      labels:
        app: payment-deployment
    spec:
      containers:
        - name: payment-service
          image: europe-west4-docker.pkg.dev/acoustic-atom-468009-u9/order-system-repository/payment.service:0.0.1-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/postgres?currentSchema=payment&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless.kafka.svc.cluster.local:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry.kafka.svc.cluster.local:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: default
  labels:
    app: payment-service
spec:
  selector:
    app: payment-deployment
  ports:
    - name: payment-service-port
      protocol: TCP
      port: 8182
  type: LoadBalancer
  loadBalancerIP: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deployment
  namespace: default
  labels:
    app: stock-deployment
spec:
  selector:
    matchLabels:
      app: stock-deployment
  template:
    metadata:
      labels:
        app: stock-deployment
    spec:
      containers:
        - name: stock-service
          image: europe-west4-docker.pkg.dev/acoustic-atom-468009-u9/order-system-repository/stock.service:0.0.1-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/postgres?currentSchema=stock&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless.kafka.svc.cluster.local:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry.kafka.svc.cluster.local:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: stock-service
  namespace: default
  labels:
    app: stock-service
spec:
  selector:
    app: stock-deployment
  ports:
    - name: stock-service-port
      protocol: TCP
      port: 8183
  type: LoadBalancer
  loadBalancerIP: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer-deployment
spec:
  selector:
    matchLabels:
      app: customer-deployment
  template:
    metadata:
      labels:
        app: customer-deployment
    spec:
      containers:
        - name: customer-service
          image: com.order.system/customer.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless.kafka.svc.cluster.local:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry.kafka.svc.cluster.local:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: default
  labels:
    app: customer-service
spec:
  selector:
    app: customer-deployment
  ports:
    - name: customer-service-port
      protocol: TCP
      port: 8184
  type: LoadBalancer
  loadBalancerIP: ""